### ISSUE TITLE
Request: Create a tag with just major version

### ISSUE THREAD

**Issue by MaxAnderson95** [cloudsmith-io/cloudsmith-cli-action#5]
The standard convention that most GitHub actions use is to create and keep updating an additional git tag that points to the most recent release in that major version, using simply the major version of that release as the tag value. This allows consumers of the action to simply reference it like this:

```yaml
- name: Use an action
   uses: cloudsmith-io/cloudsmith-cli-action@v1
   with:
      ...
```
rather than the full symver:
```yaml
- name: Use an action
   uses: cloudsmith-io/cloudsmith-cli-action@v1.0.3
   with:
      ...
```

The benefit is they can receive updates to this action over time without needing to explicitly update their action manifests. As long as the action's releases follow symver semantics, and that breaking changes result in a new major version (ex. @v2) then this should be okay.

Could a step be added to the release pipeline of `cloudsmith-io/cloudsmith-cli-action` be added that force pushes a tag with the major version?
